Repository TIP-ZIP/TIPZIP_FE, pull requests merged in 2024-11, with the labels that each got.

#3 Chore: 프로젝트 레이아웃 세팅
  .prettierrc
  README.md
  eslint.config.js
  package.json
  src/App.css
  src/App.tsx
  src/api/axios.ts
  src/assets/svgs/react.svg
  src/components/header/Header.tsx
  src/components/layout/Layout.Styled.tsx
  src/components/layout/Layout.tsx
  src/index.css
  src/main.tsx
  src/pages/home/Home.Styled.tsx
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/onboarding/OnBoarding.tsx
  src/pages/post/Post.tsx
  src/pages/scrap/Scrap.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: setup

#5 Style: 글로벌 스타일 가이드 작성 및 src/layout 위치 변경
  index.html
  src/App.tsx
  src/layout/Layout.Styled.ts
  src/layout/Layout.tsx
  src/main.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
  src/styles/theme/colors.ts
  src/styles/theme/theme.ts
  src/styles/theme/typography.ts
  tsconfig.json
  vite.config.ts
Labels: style

#8 Feature: 온보딩 및 로그인 페이지 UI 구현
  package.json
  src/App.tsx
  src/assets/pngs/google-icon.png
  src/assets/pngs/kakao-icon.png
  src/assets/pngs/naver-icon.png
  src/assets/svgs/TipZipLogo.svg
  src/assets/svgs/naver-icon.svg
  src/assets/svgs/react.svg
  src/components/Icons/TipZipLogo.ts
  src/layout/Layout.Styled.ts
  src/layout/Layout.tsx
  src/pages/SetUsername/SetUsername.styled.ts
  src/pages/SetUsername/SetUsername.tsx
  src/pages/login/Login.styled.ts
  src/pages/login/Login.tsx
  src/pages/onboarding/OnBoarding.styled.ts
  src/pages/onboarding/OnBoarding.tsx
  src/styles/theme/colors.ts
  src/styles/theme/typography.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feature

#9 Feature: 홈화면 및 로그인 모달, 헤더, 검색창 UI 구현
  src/App.tsx
  src/assets/svgs/ArrowDown.svg
  src/assets/svgs/ArrowLeft.svg
  src/assets/svgs/Bookmark.svg
  src/assets/svgs/DeleteModal.svg
  src/assets/svgs/EmptyBookmark.svg
  src/assets/svgs/FilledBookmark.svg
  src/assets/svgs/Logo.svg
  src/assets/svgs/Profile.svg
  src/assets/svgs/Search.svg
  src/assets/svgs/defaultProfile.svg
  src/assets/svgs/plus.svg
  src/assets/svgs/postexample.svg
  src/assets/svgs/star.svg
  src/assets/svgs/whiteStar.svg
  src/components/button/HomeButton.tsx
  src/components/button/TopButton.tsx
  src/components/header/Header.Styled.ts
  src/components/header/Header.tsx
  src/components/home/CategoryList/CategoryList.Styled.ts
  src/components/home/CategoryList/CategoryList.tsx
  src/components/home/Dropdown/DropDown.tsx
  src/components/home/Dropdown/Dropdown.Styled.ts
  src/components/home/LoginModalContainer.tsx
  src/components/home/PostList/PostList.Styled.ts
  src/components/home/PostList/PostList.tsx
  src/components/home/SearchBar/SearchBar.Styled.ts
  src/components/home/SearchBar/SearchBar.tsx
  src/components/home/SelectBar/SelectBar.Styled.ts
  src/components/home/SelectBar/SelectBar.tsx
  src/components/modal/LoginModal.Styled.ts
  src/components/modal/LoginModal.tsx
  src/layout/Layout.Styled.ts
  src/layout/Layout.tsx
  src/main.tsx
  src/pages/home/Home.Styled.tsx
  src/pages/home/Home.tsx
  src/pages/search/SearchPost.Styled.ts
  src/pages/search/SearchPost.tsx
  src/styles/theme/typography.ts
  vite.config.ts
Labels: feature

#12 Feature: 게시글 작성 페이지 UI 구현
  package.json
  src/App.tsx
  src/assets/svgs/camera.svg
  src/assets/svgs/leftarrow.svg
  src/assets/svgs/rightarrow.svg
  src/assets/svgs/video.svg
  src/components/post/PostEditor.styled.ts
  src/components/post/PostEditor.tsx
  src/components/post/PostHeader.styled.ts
  src/components/post/PostHeader.tsx
  src/components/post/PostLink.styled.ts
  src/components/post/PostLink.tsx
  src/components/post/PostTitle.styled.ts
  src/components/post/PostTitle.tsx
  src/components/post/TagSelector.styled.ts
  src/components/post/TagSelector.tsx
  src/pages/post/Post.styled.ts
  src/pages/post/Post.tsx
  src/styles/theme/typography.ts
  vite.config.ts
  yarn.lock
Labels: feature

#18 Feature: 게시물 상세 페이지 UI 구현 및 API 연동 Simulation
  public/data/post-detail/post-detail.json
  public/data/post-detail/post_image-1.jpg
  public/data/post-detail/post_image-2.jpg
  public/data/post-detail/post_image-3.jpg
  public/data/post-detail/profile-dummy.jpg
  src/App.tsx
  src/api/checkDuplicate.ts
  src/assets/svgs/EmptyBlackBookmark.svg
  src/assets/svgs/certificationBadge.svg
  src/assets/svgs/link.svg
  src/components/Icons/LeftArrow.ts
  src/components/header/Header.Styled.ts
  src/components/header/Header.tsx
  src/components/home/PostList/PostList.tsx
  src/layout/Layout.tsx
  src/pages/PostDetail/PostDetail.styled.ts
  src/pages/PostDetail/PostDetail.tsx
  src/pages/SetUsername/SetUsername.styled.ts
  src/pages/SetUsername/SetUsername.tsx
  src/pages/login/Login.styled.ts
  src/pages/onboarding/OnBoarding.styled.ts
  src/pages/onboarding/OnBoarding.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme/colors.ts
  src/utils/setVhProperty.ts
Labels: feature, API
