Repository TIP-ZIP/TIPZIP_FE, pull requests merged in 2024-12, with the labels that each got.

#20 Feature: 스크랩 모달 UI 구현 및 페이지 연결
  src/assets/svgs/EmptyFolder.svg
  src/assets/svgs/EmptyGrayBookmark.svg
  src/assets/svgs/FilledGrayBookmark.svg
  src/assets/svgs/OrangePlusPost.svg
  src/assets/svgs/PlusPost.svg
  src/assets/svgs/WhiteEdit.svg
  src/assets/svgs/orangebubble.svg
  src/components/home/PostList/PostList.Styled.ts
  src/components/home/PostList/PostList.tsx
  src/components/mypage/Editor/Editor.tsx
  src/components/mypage/EditorSection/EditorSection.Styled.ts
  src/components/mypage/EditorSection/EditorSection.tsx
  src/components/mypage/PostSection/PostSection.Styled.ts
  src/components/mypage/ProfileSection/ProfileSection.Styled.ts
  src/components/post/PostHeader.styled.ts
  src/components/post/PostHeader.tsx
  src/components/postdetail/ScrapEditorSection.tsx
  src/components/postdetail/ZipContainer.Styled.ts
  src/components/postdetail/ZipContainer.tsx
  src/pages/PostDetail/PostDetail.tsx
  src/pages/home/Home.Styled.tsx
  src/pages/home/Home.tsx
  src/pages/mypage/Mypage.Styled.ts
  src/pages/mypage/Mypage.tsx
  src/pages/post/Post.tsx
Labels: feature

#23 Feature: 스크랩 페이지 UI 구현
  src/App.tsx
  src/assets/pngs/plusSign.png
  src/assets/svgs/ArrowLeftWhite.svg
  src/assets/svgs/ColoredBookmark.svg
  src/assets/svgs/DeleteWhite.svg
  src/assets/svgs/EditWhite.svg
  src/assets/svgs/ScrapHeader.svg
  src/assets/svgs/newScrapFolder.svg
  src/assets/svgs/newScrapFolderSelected.svg
  src/assets/svgs/personalScrapFolder.svg
  src/assets/svgs/personalScrapFolderSelected.svg
  src/assets/svgs/scrapDelete.svg
  src/assets/svgs/scrapFolder.svg
  src/assets/svgs/scrapFolderSelected.svg
  src/assets/svgs/scrapOption.svg
  src/assets/svgs/scrapOptionDropdown.svg
  src/components/header/Header.tsx
  src/components/home/CategoryList/CategoryList.Styled.ts
  src/components/home/CategoryList/CategoryList.tsx
  src/components/post/PostHeader.styled.ts
  src/components/scrap/ScrapFolder.Styled.ts
  src/components/scrap/ScrapFolder.tsx
  src/pages/scrap/Scrap.Styled.ts
  src/pages/scrap/Scrap.tsx
  src/pages/scrap/ScrapFolderView.Styled.ts
  src/pages/scrap/ScrapFolderView.tsx
  src/pages/scrap/ScrapPostView.Styled.ts
  src/pages/scrap/ScrapPostView.tsx
  src/styles/theme/colors.ts
Labels: feature

#26 Feat: 카카오 로그인 API 구현
  src/App.tsx
  src/api/axios.ts
  src/api/checkDuplicate.ts
  src/auth/redirects/KakaoRedirect.tsx
  src/auth/utils/authHelpers.ts
  src/pages/SetUsername/SetUsername.tsx
  src/pages/login/Login.tsx
  tsconfig.json
  vite.config.ts
Labels: API, social login

#28 Revert "Feat: 카카오 로그인 API 구현 (#26)"
  src/App.tsx
  src/api/axios.ts
  src/api/checkDuplicate.ts
  src/auth/redirects/KakaoRedirect.tsx
  src/auth/utils/authHelpers.ts
  src/pages/SetUsername/SetUsername.tsx
  src/pages/login/Login.tsx
  tsconfig.json
  vite.config.ts
Labels: revert

#31 Revert "Revert "Feat: 카카오 로그인 API 구현 (#26)""
  src/App.tsx
  src/api/axios.ts
  src/api/checkDuplicate.ts
  src/auth/redirects/KakaoRedirect.tsx
  src/auth/utils/authHelpers.ts
  src/pages/SetUsername/SetUsername.tsx
  src/pages/login/Login.tsx
  tsconfig.json
  vite.config.ts
Labels: revert

#32 Feat: 홈 post api 연결 및 마이페이지 api 연결
  src/App.tsx
  src/components/header/Header.tsx
  src/components/home/CategoryList/CategoryList.Styled.ts
  src/components/home/Dropdown/Dropdown.Styled.ts
  src/components/home/PostList/PostList.tsx
  src/components/mypage/EditorSection/EditorSection.tsx
  src/components/mypage/ProfileSection/ProfileSection.tsx
  src/hooks/home/useCategory.ts
  src/hooks/home/useSort.ts
  src/hooks/useAuth.ts
  src/pages/home/Home.tsx
  src/pages/mypage/Mypage.tsx
  tsconfig.json
  vite.config.ts
Labels: feature, API

#35 Feature: 검색창 UI 및 api 연결
  src/App.tsx
  src/assets/svgs/whiteSearch.svg
  src/components/home/PostList/PostList.Styled.ts
  src/components/home/PostList/PostList.tsx
  src/components/home/SearchBar/SearchBar.Styled.ts
  src/components/home/SearchBar/SearchBar.tsx
  src/components/mypage/EditorSection/EditorSection.Styled.ts
  src/components/post/TagSelector.tsx
  src/components/postdetail/Spinner.tsx
  src/constants/PostData.ts
  src/constants/TagData.ts
  src/pages/PostDetail/PostDetail.tsx
  src/pages/home/Home.Styled.tsx
  src/pages/home/Home.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/search/SearchPost.Styled.ts
  src/pages/search/SearchPost.tsx
Labels: feature, API

#37 Feat: 네이버 로그인 API 구현
  src/App.tsx
  src/auth/redirects/NaverRedirect.tsx
  src/pages/login/Login.tsx
Labels: API, social login

#39 Feat: 게시글 작성 api 연결
  src/components/post/PostEditor.tsx
  src/pages/post/Post.tsx
Labels: API

#41 Fix: API 관련 로직 수정
  src/api/axios.ts
  src/api/checkDuplicate.ts
  src/auth/redirects/GoogleRedirect.tsx
  src/auth/redirects/KakaoRedirect.tsx
  src/auth/redirects/NaverRedirect.tsx
  src/components/home/PostList/PostList.Styled.ts
  src/components/home/PostList/PostList.tsx
  src/components/home/SearchBar/SearchBar.tsx
  src/pages/PostDetail/PostDetail.tsx
  src/pages/SetUsername/SetUsername.tsx
  src/pages/home/Home.tsx
  src/pages/search/SearchPost.tsx
Labels: bug, API

#40 Feat: 사용자 이름 API 구현
  src/App.tsx
  src/api/axios.ts
  src/api/username/checkDuplicate.ts
  src/api/username/setUsername.ts
  src/auth/redirects/GoogleRedirect.tsx
  src/auth/redirects/KakaoRedirect.tsx
  src/auth/redirects/NaverRedirect.tsx
  src/pages/SetUsername/SetUsername.tsx
  src/pages/login/Login.tsx
Labels: feature, API

#44 Fix: 게시글 작성 API 수정
  src/components/post/PostEditor.tsx
  src/pages/post/Post.tsx
Labels: API

#45 Feat: 로그아웃 및 Access Token 재발급 API 구현
  src/api/axios.ts
  src/auth/redirects/GoogleRedirect.tsx
  src/auth/redirects/KakaoRedirect.tsx
  src/auth/redirects/NaverRedirect.tsx
  src/components/header/Header.tsx
  src/hooks/useAuth.ts
Labels: API, auth

#46 Feat: 마이페이지 api 전체 연결
  src/App.tsx
  src/assets/svgs/googleIcon.svg
  src/assets/svgs/kakaoIcon.svg
  src/assets/svgs/naverIcon.svg
  src/components/home/PostList/PostList.Styled.ts
  src/components/home/PostList/PostList.tsx
  src/components/mypage/EditorSection/EditorSection.tsx
  src/components/mypage/PostSection/PostSection.tsx
  src/components/mypage/ProfileSection/ProfileSection.Styled.ts
  src/components/mypage/ProfileSection/ProfileSection.tsx
  src/components/post/PostEditor.styled.ts
  src/pages/PostDetail/PostDetail.tsx
  src/pages/home/Home.Styled.tsx
  src/pages/home/Home.tsx
  src/pages/mypage/Mypage.tsx
Labels: bug, feature, API

#48 Feat: 스크랩 모달 api 연결
  src/components/home/PostList/PostList.Styled.ts
  src/components/home/PostList/PostList.tsx
  src/components/mypage/EditorSection/EditorSection.Styled.ts
  src/components/mypage/EditorSection/EditorSection.tsx
  src/components/postdetail/ScrapEditorSection.tsx
  src/components/postdetail/ZipContainer.tsx
  src/constants/PostData.ts
  src/hooks/home/useCategory.ts
  src/hooks/useAuth.ts
  src/pages/home/Home.tsx
Labels: bug, API

#50 Feat: 스크랩 페이지 api 연결
  src/components/post/PostEditor.styled.ts
  src/hooks/useAuth.ts
  src/pages/scrap/Scrap.tsx
  src/pages/scrap/ScrapFolderView.Styled.ts
  src/pages/scrap/ScrapFolderView.tsx
  src/pages/scrap/ScrapPostView.tsx
Labels: feature, API

#51 Feat: 포스트 에디터 Quill 적용
  package.json
  src/components/post/PostEditor.styled.ts
  src/components/post/PostEditor.tsx
  src/components/post/PostView.tsx
  src/pages/PostDetail/PostDetail.styled.ts
  src/pages/PostDetail/PostDetail.tsx
  yarn.lock
Labels: feature

#52 FIx: Quill 에디터 UI 수정
  src/components/post/PostEditor.styled.ts
Labels: feature

#53 Feat: thumbnail form UI 및 api 연결
  src/components/home/PostList/PostList.Styled.ts
  src/components/home/PostList/PostList.tsx
  src/components/post/PostEditor.tsx
  src/components/post/PostThumbnail.Styled.ts
  src/components/post/PostThumbnail.tsx
  src/components/postdetail/ZipContainer.tsx
  src/pages/post/Post.styled.ts
  src/pages/post/Post.tsx
  yarn.lock
Labels: bug, API

#54 Feat: 게시글 삭제 API 구현
  index.html
  public/tipzip.svg
  public/vite.svg
  src/assets/svgs/PostDeleteIcon.svg
  src/assets/svgs/PostEditIcon.svg
  src/assets/svgs/elipsisIcon.svg
  src/components/header/Header.tsx
  src/components/modal/Modal.tsx
  src/components/modal/PostDeleteModal.tsx
  src/components/mypage/ProfileSection/ProfileSection.tsx
  src/components/postdetail/PostManageDropdonw/PostManageDropdown.tsx
  src/components/postdetail/PostManageDropdonw/PostMangeDropdown.styled.ts
  src/components/scrap/ScrapFolder.tsx
  src/hooks/useAuth.ts
  src/pages/PostDetail/PostDetail.styled.ts
  src/pages/PostDetail/PostDetail.tsx
  src/pages/home/Home.Styled.tsx
  src/pages/home/Home.tsx
  src/pages/mypage/Mypage.tsx
Labels: feature, API
